site_name: HackAllTheThings
dev_addr: "127.0.0.1:3000"
site_url: 'https://notes.akenofu.me'
repo_url: 'https://github.com/akenofu/HackAllTheThings'
edit_uri: 'https://github.com/akenofu/HackAllTheThings/tree/master/docs/'
site_description: 'This repo is my personal repertoire of technology and security-related notes since day one in the field. It is also my attempt to give back to the infosec community. It has all the references, checklists, cheat sheets, and notes I use daily. I forgot to say, I am very forgetful 🙋‍♂️. So, I am probably the person who uses this the most 👀'
site_author: 'Karim Mohamed @akenofu'
watch: ['docs', 'mkdocs.yml', 'custom_theme']
plugins:
    - search:
        indexing: 'full'

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.superfences 
    - tables
    - toc
    - pymdownx.tasklist:
        custom_checkbox: true
        clickable_checkbox: true
    - footnotes        

theme:
    name: material
    site_url: 'https://notes.akenofu.me'
    highlightjs: true
    github_url: https://github.com/akenofu/HackAllTheThings
    navigation_depth: 4
    titles_only: true
    sticky_navigation: true
    collapse_navigation: true
    custom_dir: custom_theme
    theme:
    logo: Screenshots/logo.png
    favicon: Screenshots/logo.png
    palette:
       # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
            # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode


 